baseURL = "https://mikhail.io/"
languageCode = "en-us"
title = "Mikhail Shilkov"
copyright = "Mikhail Shilkov - All rights reserved"

assetDir = "assets"
summaryLength = 25
enableEmoji = true

pygmentsCodeFences = true
pygmentsStyle = "vs"
googleAnalytics = "UA-59218480-1"
disqusShortname = "mikhailio"

[outputs]
  home     = ["HTML", "XML"]
  section  = ["HTML"]

[mediaTypes."application/xml"]
  suffixes = [""]
  delimiter = ""

[outputFormats.XML]
  mediatype = "application/xml"
  baseName = "feed"

[params]
  favicon = "/favicon.ico"
  description ="Serverless, Cloud, Azure, AWS, F#, Functional Programming, and more"
  feedSections="2019"

[params.author]
  name = "Mikhail Shilkov"
  thumbnail = "/images/author.jpg"

[params.index]
  title = "Mikhail Shilkov"

[params.social]
  linkedin = "MikhailShilkov"
  github = "MikhailShilkov"
  twitter = "MikhailShilkov"
  medium = "MikhailShilkov"
  devto = "mikhailshilkov"

## Main Menu
[[menu.main]]
    name = "TOPICS"
    weight = 100
    identifier = "topics"
    url = "/tags/"
[[menu.main]]
    name = "ARCHIVES"
    weight = 200
    identifier = "archives"
    url = "/archives/"
[[menu.main]]
    name = "LABS"
    weight = 300
    identifier = "labs"
    url = "/lab/"
[[menu.main]]
    name = "TALKS"
    weight = 400
    identifier = "talks"
    url = "/talks/"
[[menu.main]]
    name = "ABOUT"
    weight = 500
    identifier = "about"
    url = "/about/"

## talks
[[params.talks]]
    year = 2020
    date = "Feb 25"
    title = "Azure Infrastructure as C# and F#"
    link = "https://www.microsoft.com/cs-cz/ignite-the-tour/prague"
    event = "Microsoft Ignite The Tour | Prague"
    slides = "https://speakerdeck.com/mikhailshilkov/azure-infrastructure-as-c-number-and-f-number"
[[params.talks]]
    year = 2020
    date = "Feb 20"
    title = "Cloud Infrastructure as C# and F# with Pulumi"
    link = "https://www.meetup.com/dutchdotnet/events/267776963"
    event = "Dutch .Net Group"
    slides = "https://speakerdeck.com/mikhailshilkov/pulumi-cloud-infrastructure-as-c-number-and-f-number"
    video = "https://www.youtube.com/watch?v=zHjz-yTg0qI"
[[params.talks]]
    year = 2020
    date = "Feb 19"
    title = "Cloud Infrastructure as C# and F# with Pulumi"
    link = "https://www.meetup.com/Skane-Azure-User-Group/events/268057791/"
    event = "Skåne Azure User Group, Malmö, Sweden"
    slides = "https://speakerdeck.com/mikhailshilkov/pulumi-cloud-infrastructure-as-c-number-and-f-number"
    video = "https://www.youtube.com/watch?v=0qkkRRysqe8"
[[params.talks]]
    year = 2020
    date = "Feb 18"
    title = "Cloud Infrastructure as C# and F# with Pulumi"
    link = "https://www.meetup.com/Copenhagen-Net-User-Group/events/268445025/"
    event = "Copenhagen .NET user group"
    slides = "https://speakerdeck.com/mikhailshilkov/pulumi-cloud-infrastructure-as-c-number-and-f-number"
[[params.talks]]
    year = 2020
    date = "Feb 18"
    title = "Workshop: Azure Infrastructure as Code with Pulumi and C#"
    link = "https://www.meetup.com/Azure-Usergroup-Denmark/events/268445103/"
    event = "Azure Usergroup Denmark"
    slides = "https://github.com/pulumi/infrastructure-as-code-workshop/blob/master/labs/azure/csharp/Infrastructure%20as%20Code%20Workshop%20Azure.pdf"
    labs = "https://github.com/pulumi/infrastructure-as-code-workshop/tree/master/labs/azure/csharp"
[[params.talks]]
    year = 2020
    date = "Feb 17"
    title = "Introduction to F# and Functional Programming"
    link = "https://www.meetup.com/dotnet-amsterdam/events/267228367/"
    event = "dotnet Amsterdam meetup"
    slides = "https://mikhail.io/talks/why-fsharp2/"
    video = "https://www.youtube.com/watch?v=F5bm2em5kRU"
[[params.talks]]
    year = 2020
    date = "Feb 12"
    title = "Cloud Infrastructure as C# and F# with Pulumi"
    link = "https://www.meetup.com/dotnetsouthwest/events/268110936/"
    event = ".NET South West meetup, Bristol, UK"
    slides = "https://speakerdeck.com/mikhailshilkov/pulumi-cloud-infrastructure-as-c-number-and-f-number"
[[params.talks]]
    year = 2020
    date = "Feb 11"
    title = "Cloud Infrastructure as C# and F# with Pulumi"
    link = "https://www.meetup.com/dotnetsoutheast/events/268137504/"
    event = ".NET South East meetup, Brighton, UK"
    slides = "https://speakerdeck.com/mikhailshilkov/pulumi-cloud-infrastructure-as-c-number-and-f-number"
[[params.talks]]
    year = 2020
    date = "Jan 30"
    title = "Cloud Infrastructure as C# and F# with Pulumi"
    link = "https://www.meetup.com/netcorebcn/events/267108105/"
    event = "Barcelona .NET Core meetup"
    slides = "https://speakerdeck.com/mikhailshilkov/pulumi-cloud-infrastructure-as-c-number-and-f-number"
[[params.talks]]
    year = 2020
    date = "Jan 17"
    title = "Cloud Infrastructure as C# and F# with Pulumi"
    link = "https://dotnetfriday.nl"
    event = "DotNetFriday, Utrecht, NL"
    slides = "https://speakerdeck.com/mikhailshilkov/pulumi-cloud-infrastructure-as-c-number-and-f-number"
